// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPU")
extern class GPU {
	var wgslLanguageFeatures(default, null):WGSLLanguageFeatures;
	function getPreferredCanvasFormat():GPUTextureFormat;
	function requestAdapter(?options:GPURequestAdapterOptions):js.lib.Promise<Null<GPUAdapter>>;
}
