// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUAddressMode(String) to String {
	var CLAMP_TO_EDGE = "clamp-to-edge";
	var REPEAT = "repeat";
	var MIRROR_REPEAT = "mirror-repeat";
}
