// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUAdapter")
extern class GPUAdapter {
	var features(default, null):GPUSupportedFeatures;
	var limits(default, null):GPUSupportedLimits;
	var info(default, null):GPUAdapterInfo;
	function requestDevice(?descriptor:GPUDeviceDescriptor):js.lib.Promise<GPUDevice>;
}
