// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUAdapterInfo")
extern class GPUAdapterInfo {
	var vendor(default, null):String;
	var architecture(default, null):String;
	var device(default, null):String;
	var description(default, null):String;
	var subgroupMinSize(default, null):Int;
	var subgroupMaxSize(default, null):Int;
	var isFallbackAdapter(default, null):Bool;
}
