// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUBuffer")
extern class GPUBuffer {
	var size(default, null):Float;
	var usage(default, null):Int;
	var mapState(default, null):GPUBufferMapState;
	var label:String;
	function destroy():Void;
	function getMappedRange(?offset:Float, ?size:Float):js.lib.BufferSource;
	function mapAsync(mode:Int, ?offset:Float, ?size:Float):js.lib.Promise<Void>;
	function unmap():Void;
}
