// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUBufferMapState(String) to String {
	var UNMAPPED = "unmapped";
	var PENDING = "pending";
	var MAPPED = "mapped";
}
