// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUBlendOperation(String) to String {
	var ADD = "add";
	var SUBTRACT = "subtract";
	var REVERSE_SUBTRACT = "reverse-subtract";
	var MIN = "min";
	var MAX = "max";
}
