// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBufferBinding = {
	var buffer:GPUBuffer;
	@:optional var offset:Float;
	@:optional var size:Float;
}
