// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBufferBindingLayout = {
	@:optional var type:GPUBufferBindingType;
	@:optional var hasDynamicOffset:Bool;
	@:optional var minBindingSize:Float;
}
