// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBindGroupDescriptor = {
	@:optional var label:String;
	var layout:GPUBindGroupLayout;
	var entries:Array<GPUBindGroupEntry>;
}
