// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBlendComponent = {
	@:optional var operation:GPUBlendOperation;
	@:optional var srcFactor:GPUBlendFactor;
	@:optional var dstFactor:GPUBlendFactor;
}
