// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBindGroupLayoutDescriptor = {
	@:optional var label:String;
	var entries:Array<GPUBindGroupLayoutEntry>;
}
