// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBufferDescriptor = {
	@:optional var label:String;
	var size:Float;
	var usage:Int;
	@:optional var mappedAtCreation:Bool;
}
