// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUBufferBindingType(String) to String {
	var UNIFORM = "uniform";
	var STORAGE = "storage";
	var READ_ONLY_STORAGE = "read-only-storage";
}
