// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUBindGroupLayoutEntry = {
	var binding:Int;
	var visibility:Int;
	@:optional var buffer:GPUBufferBindingLayout;
	@:optional var sampler:GPUSamplerBindingLayout;
	@:optional var texture:GPUTextureBindingLayout;
	@:optional var storageTexture:GPUStorageTextureBindingLayout;
	@:optional var externalTexture:GPUExternalTextureBindingLayout;
}
