// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUComputePassEncoder")
extern class GPUComputePassEncoder {
	var label:String;
	function dispatchWorkgroups(workgroupCountX:Int, ?workgroupCountY:Int, ?workgroupCountZ:Int):Void;
	function dispatchWorkgroupsIndirect(indirectBuffer:GPUBuffer, indirectOffset:Float):Void;
	function end():Void;
	function insertDebugMarker(markerLabel:String):Void;
	function popDebugGroup():Void;
	function pushDebugGroup(groupLabel:String):Void;
	@:overload(function(index:Int, bindGroup:Null<GPUBindGroup>, ?dynamicOffsets:Array<Int>):Void {})
	function setBindGroup(index:Int, bindGroup:Null<GPUBindGroup>, dynamicOffsetsData:js.lib.BufferSource, dynamicOffsetsDataStart:Float, dynamicOffsetsDataLength:Int):Void;
	function setImmediates(rangeOffset:Int, data:js.lib.BufferSource, ?dataOffset:Float, ?dataSize:Float):Void;
	function setPipeline(pipeline:GPUComputePipeline):Void;
}
