// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUColorTargetState = {
	var format:GPUTextureFormat;
	@:optional var blend:GPUBlendState;
	@:optional var writeMask:Int;
}
