// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUComputePassTimestampWrites = {
	var querySet:GPUQuerySet;
	@:optional var beginningOfPassWriteIndex:Int;
	@:optional var endOfPassWriteIndex:Int;
}
