// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUCompilationMessage")
extern class GPUCompilationMessage {
	var message(default, null):String;
	var type(default, null):GPUCompilationMessageType;
	var lineNum(default, null):Float;
	var linePos(default, null):Float;
	var offset(default, null):Float;
	var length(default, null):Float;
}
