// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUComputePassDescriptor = {
	@:optional var label:String;
	@:optional var timestampWrites:GPUComputePassTimestampWrites;
}
