// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUCanvasToneMappingMode(String) to String {
	var STANDARD = "standard";
	var EXTENDED = "extended";
}
