// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUCompilationMessageType(String) to String {
	var ERROR = "error";
	var WARNING = "warning";
	var INFO = "info";
}
