// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUCullMode(String) to String {
	var NONE = "none";
	var FRONT = "front";
	var BACK = "back";
}
