// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUCopyExternalImageSourceInfo = {
	var source:Dynamic;
	@:optional var origin:Dynamic;
	@:optional var flipY:Bool;
}
