// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUCanvasAlphaMode(String) to String {
	var OPAQUE = "opaque";
	var PREMULTIPLIED = "premultiplied";
}
