// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUComputePipelineDescriptor = {
	@:optional var label:String;
	var layout:Dynamic;
	var compute:GPUProgrammableStage;
}
