// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUCanvasContext")
extern class GPUCanvasContext {
	var canvas(default, null):Dynamic;
	function configure(configuration:GPUCanvasConfiguration):Void;
	function getConfiguration():Null<GPUCanvasConfiguration>;
	function getCurrentTexture():GPUTexture;
	function unconfigure():Void;
}
