// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUCanvasConfiguration = {
	var device:GPUDevice;
	var format:GPUTextureFormat;
	@:optional var usage:Int;
	@:optional var viewFormats:Array<GPUTextureFormat>;
	@:optional var colorSpace:Dynamic;
	@:optional var toneMapping:GPUCanvasToneMapping;
	@:optional var alphaMode:GPUCanvasAlphaMode;
}
