// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUCommandEncoder")
extern class GPUCommandEncoder {
	var label:String;
	function beginComputePass(?descriptor:GPUComputePassDescriptor):GPUComputePassEncoder;
	function beginRenderPass(descriptor:GPURenderPassDescriptor):GPURenderPassEncoder;
	function clearBuffer(buffer:GPUBuffer, ?offset:Float, ?size:Float):Void;
	@:overload(function(source:GPUBuffer, destination:GPUBuffer, ?size:Float):Void {})
	function copyBufferToBuffer(source:GPUBuffer, sourceOffset:Float, destination:GPUBuffer, destinationOffset:Float, ?size:Float):Void;
	function copyBufferToTexture(source:GPUTexelCopyBufferInfo, destination:GPUTexelCopyTextureInfo, copySize:Dynamic):Void;
	function copyTextureToBuffer(source:GPUTexelCopyTextureInfo, destination:GPUTexelCopyBufferInfo, copySize:Dynamic):Void;
	function copyTextureToTexture(source:GPUTexelCopyTextureInfo, destination:GPUTexelCopyTextureInfo, copySize:Dynamic):Void;
	function finish(?descriptor:GPUCommandBufferDescriptor):GPUCommandBuffer;
	function insertDebugMarker(markerLabel:String):Void;
	function popDebugGroup():Void;
	function pushDebugGroup(groupLabel:String):Void;
	function resolveQuerySet(querySet:GPUQuerySet, firstQuery:Int, queryCount:Int, destination:GPUBuffer, destinationOffset:Float):Void;
}
