// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUComputePipeline")
extern class GPUComputePipeline {
	var label:String;
	function getBindGroupLayout(index:Int):GPUBindGroupLayout;
}
