// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUCopyExternalImageDestInfo = {
	var texture:GPUTexture;
	@:optional var mipLevel:Int;
	@:optional var origin:Dynamic;
	@:optional var aspect:GPUTextureAspect;
	@:optional var colorSpace:Dynamic;
	@:optional var premultipliedAlpha:Bool;
}
