// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUDepthStencilState = {
	var format:GPUTextureFormat;
	@:optional var depthWriteEnabled:Bool;
	@:optional var depthCompare:GPUCompareFunction;
	@:optional var stencilFront:GPUStencilFaceState;
	@:optional var stencilBack:GPUStencilFaceState;
	@:optional var stencilReadMask:Int;
	@:optional var stencilWriteMask:Int;
	@:optional var depthBias:Int;
	@:optional var depthBiasSlopeScale:Float;
	@:optional var depthBiasClamp:Float;
}
