// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUDeviceLostReason(String) to String {
	var UNKNOWN = "unknown";
	var DESTROYED = "destroyed";
}
