// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUDevice")
extern class GPUDevice extends js.html.EventTarget {
	var features(default, null):GPUSupportedFeatures;
	var limits(default, null):GPUSupportedLimits;
	var adapterInfo(default, null):GPUAdapterInfo;
	var queue(default, null):GPUQueue;
	var lost(default, null):js.lib.Promise<GPUDeviceLostInfo>;
	var onuncapturederror:Dynamic;
	var label:String;
	function createBindGroup(descriptor:GPUBindGroupDescriptor):GPUBindGroup;
	function createBindGroupLayout(descriptor:GPUBindGroupLayoutDescriptor):GPUBindGroupLayout;
	function createBuffer(descriptor:GPUBufferDescriptor):GPUBuffer;
	function createCommandEncoder(?descriptor:GPUCommandEncoderDescriptor):GPUCommandEncoder;
	function createComputePipeline(descriptor:GPUComputePipelineDescriptor):GPUComputePipeline;
	function createComputePipelineAsync(descriptor:GPUComputePipelineDescriptor):js.lib.Promise<GPUComputePipeline>;
	function createPipelineLayout(descriptor:GPUPipelineLayoutDescriptor):GPUPipelineLayout;
	function createQuerySet(descriptor:GPUQuerySetDescriptor):GPUQuerySet;
	function createRenderBundleEncoder(descriptor:GPURenderBundleEncoderDescriptor):GPURenderBundleEncoder;
	function createRenderPipeline(descriptor:GPURenderPipelineDescriptor):GPURenderPipeline;
	function createRenderPipelineAsync(descriptor:GPURenderPipelineDescriptor):js.lib.Promise<GPURenderPipeline>;
	function createSampler(?descriptor:GPUSamplerDescriptor):GPUSampler;
	function createShaderModule(descriptor:GPUShaderModuleDescriptor):GPUShaderModule;
	function createTexture(descriptor:GPUTextureDescriptor):GPUTexture;
	function destroy():Void;
	function importExternalTexture(descriptor:GPUExternalTextureDescriptor):GPUExternalTexture;
	function popErrorScope():js.lib.Promise<Null<GPUError>>;
	function pushErrorScope(filter:GPUErrorFilter):Void;
}
