// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUDeviceDescriptor = {
	@:optional var label:String;
	@:optional var requiredFeatures:Array<GPUFeatureName>;
	@:optional var requiredLimits:haxe.DynamicAccess<Dynamic>;
	@:optional var defaultQueue:GPUQueueDescriptor;
}
