// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUDeviceLostInfo")
extern class GPUDeviceLostInfo {
	var reason(default, null):GPUDeviceLostReason;
	var message(default, null):String;
}
