// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUExternalTextureDescriptor = {
	@:optional var label:String;
	var source:Dynamic;
	@:optional var colorSpace:Dynamic;
}
