// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUExtent3DDict = {
	var width:Int;
	@:optional var height:Int;
	@:optional var depthOrArrayLayers:Int;
}
