// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUErrorFilter(String) to String {
	var VALIDATION = "validation";
	var OUT_OF_MEMORY = "out-of-memory";
	var INTERNAL = "internal";
}
