// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUFeatureName(String) to String {
	var CORE_FEATURES_AND_LIMITS = "core-features-and-limits";
	var DEPTH_CLIP_CONTROL = "depth-clip-control";
	var DEPTH32FLOAT_STENCIL8 = "depth32float-stencil8";
	var TEXTURE_COMPRESSION_BC = "texture-compression-bc";
	var TEXTURE_COMPRESSION_BC_SLICED_3D = "texture-compression-bc-sliced-3d";
	var TEXTURE_COMPRESSION_ETC2 = "texture-compression-etc2";
	var TEXTURE_COMPRESSION_ASTC = "texture-compression-astc";
	var TEXTURE_COMPRESSION_ASTC_SLICED_3D = "texture-compression-astc-sliced-3d";
	var TIMESTAMP_QUERY = "timestamp-query";
	var INDIRECT_FIRST_INSTANCE = "indirect-first-instance";
	var SHADER_F16 = "shader-f16";
	var RG11B10UFLOAT_RENDERABLE = "rg11b10ufloat-renderable";
	var BGRA8UNORM_STORAGE = "bgra8unorm-storage";
	var FLOAT32_FILTERABLE = "float32-filterable";
	var FLOAT32_BLENDABLE = "float32-blendable";
	var CLIP_DISTANCES = "clip-distances";
	var DUAL_SOURCE_BLENDING = "dual-source-blending";
	var SUBGROUPS = "subgroups";
	var TEXTURE_FORMATS_TIER1 = "texture-formats-tier1";
	var TEXTURE_FORMATS_TIER2 = "texture-formats-tier2";
	var PRIMITIVE_INDEX = "primitive-index";
	var TEXTURE_COMPONENT_SWIZZLE = "texture-component-swizzle";
	var SUBGROUP_SIZE_CONTROL = "subgroup-size-control";
	var TEXTURE_COMPRESSION_UNALIGNED = "texture-compression-unaligned";
}
