// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUFragmentState = {
	var module:GPUShaderModule;
	@:optional var entryPoint:String;
	@:optional var constants:haxe.DynamicAccess<Float>;
	var targets:Array<Null<GPUColorTargetState>>;
}
