// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUMultisampleState = {
	@:optional var count:Int;
	@:optional var mask:Int;
	@:optional var alphaToCoverageEnabled:Bool;
}
