// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUPowerPreference(String) to String {
	var LOW_POWER = "low-power";
	var HIGH_PERFORMANCE = "high-performance";
}
