// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUPrimitiveTopology(String) to String {
	var POINT_LIST = "point-list";
	var LINE_LIST = "line-list";
	var LINE_STRIP = "line-strip";
	var TRIANGLE_LIST = "triangle-list";
	var TRIANGLE_STRIP = "triangle-strip";
}
