// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUPipelineError")
extern class GPUPipelineError extends Dynamic {
	var reason(default, null):GPUPipelineErrorReason;
}
