// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUPrimitiveState = {
	@:optional var topology:GPUPrimitiveTopology;
	@:optional var stripIndexFormat:GPUIndexFormat;
	@:optional var frontFace:GPUFrontFace;
	@:optional var cullMode:GPUCullMode;
	@:optional var unclippedDepth:Bool;
}
