// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUPipelineLayoutDescriptor = {
	@:optional var label:String;
	var bindGroupLayouts:Array<Null<GPUBindGroupLayout>>;
	@:optional var immediateSize:Int;
}
