// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUPipelineErrorReason(String) to String {
	var VALIDATION = "validation";
	var INTERNAL = "internal";
}
