// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUProgrammableStage = {
	var module:GPUShaderModule;
	@:optional var entryPoint:String;
	@:optional var constants:haxe.DynamicAccess<Float>;
}
