// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUQuerySet")
extern class GPUQuerySet {
	var type(default, null):GPUQueryType;
	var count(default, null):Int;
	var label:String;
	function destroy():Void;
}
