// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUQueue")
extern class GPUQueue {
	var label:String;
	function copyExternalImageToTexture(source:GPUCopyExternalImageSourceInfo, destination:GPUCopyExternalImageDestInfo, copySize:Dynamic):Void;
	function onSubmittedWorkDone():js.lib.Promise<Void>;
	function submit(commandBuffers:Array<GPUCommandBuffer>):Void;
	function writeBuffer(buffer:GPUBuffer, bufferOffset:Float, data:js.lib.BufferSource, ?dataOffset:Float, ?size:Float):Void;
	function writeTexture(destination:GPUTexelCopyTextureInfo, data:js.lib.BufferSource, dataLayout:GPUTexelCopyBufferLayout, size:Dynamic):Void;
}
