// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderPipelineDescriptor = {
	@:optional var label:String;
	var layout:Dynamic;
	var vertex:GPUVertexState;
	@:optional var primitive:GPUPrimitiveState;
	@:optional var depthStencil:GPUDepthStencilState;
	@:optional var multisample:GPUMultisampleState;
	@:optional var fragment:GPUFragmentState;
}
