// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderPassDepthStencilAttachment = {
	var view:Dynamic;
	@:optional var depthClearValue:Float;
	@:optional var depthLoadOp:GPULoadOp;
	@:optional var depthStoreOp:GPUStoreOp;
	@:optional var depthReadOnly:Bool;
	@:optional var stencilClearValue:Int;
	@:optional var stencilLoadOp:GPULoadOp;
	@:optional var stencilStoreOp:GPUStoreOp;
	@:optional var stencilReadOnly:Bool;
}
