// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderPassDescriptor = {
	@:optional var label:String;
	var colorAttachments:Array<Null<GPURenderPassColorAttachment>>;
	@:optional var depthStencilAttachment:GPURenderPassDepthStencilAttachment;
	@:optional var occlusionQuerySet:GPUQuerySet;
	@:optional var timestampWrites:GPURenderPassTimestampWrites;
	@:optional var maxDrawCount:Float;
}
