// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderBundleEncoderDescriptor = {
	@:optional var label:String;
	var colorFormats:Array<Null<GPUTextureFormat>>;
	@:optional var depthStencilFormat:GPUTextureFormat;
	@:optional var sampleCount:Int;
	@:optional var depthReadOnly:Bool;
	@:optional var stencilReadOnly:Bool;
}
