// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderPassColorAttachment = {
	var view:Dynamic;
	@:optional var depthSlice:Int;
	@:optional var resolveTarget:Dynamic;
	@:optional var clearValue:Dynamic;
	var loadOp:GPULoadOp;
	var storeOp:GPUStoreOp;
}
