// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPURenderPipeline")
extern class GPURenderPipeline {
	var label:String;
	function getBindGroupLayout(index:Int):GPUBindGroupLayout;
}
