// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURenderPassLayout = {
	@:optional var label:String;
	var colorFormats:Array<Null<GPUTextureFormat>>;
	@:optional var depthStencilFormat:GPUTextureFormat;
	@:optional var sampleCount:Int;
}
