// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPURenderBundleEncoder")
extern class GPURenderBundleEncoder {
	var label:String;
	function draw(vertexCount:Int, ?instanceCount:Int, ?firstVertex:Int, ?firstInstance:Int):Void;
	function drawIndexed(indexCount:Int, ?instanceCount:Int, ?firstIndex:Int, ?baseVertex:Int, ?firstInstance:Int):Void;
	function drawIndexedIndirect(indirectBuffer:GPUBuffer, indirectOffset:Float):Void;
	function drawIndirect(indirectBuffer:GPUBuffer, indirectOffset:Float):Void;
	function finish(?descriptor:GPURenderBundleDescriptor):GPURenderBundle;
	function insertDebugMarker(markerLabel:String):Void;
	function popDebugGroup():Void;
	function pushDebugGroup(groupLabel:String):Void;
	@:overload(function(index:Int, bindGroup:Null<GPUBindGroup>, ?dynamicOffsets:Array<Int>):Void {})
	function setBindGroup(index:Int, bindGroup:Null<GPUBindGroup>, dynamicOffsetsData:js.lib.BufferSource, dynamicOffsetsDataStart:Float, dynamicOffsetsDataLength:Int):Void;
	function setImmediates(rangeOffset:Int, data:js.lib.BufferSource, ?dataOffset:Float, ?dataSize:Float):Void;
	function setIndexBuffer(buffer:GPUBuffer, indexFormat:GPUIndexFormat, ?offset:Float, ?size:Float):Void;
	function setPipeline(pipeline:GPURenderPipeline):Void;
	function setVertexBuffer(slot:Int, buffer:Null<GPUBuffer>, ?offset:Float, ?size:Float):Void;
}
