// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPURequestAdapterOptions = {
	@:optional var featureLevel:String;
	@:optional var powerPreference:GPUPowerPreference;
	@:optional var forceFallbackAdapter:Bool;
	@:optional var xrCompatible:Bool;
}
