// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUSamplerBindingType(String) to String {
	var FILTERING = "filtering";
	var NON_FILTERING = "non-filtering";
	var COMPARISON = "comparison";
}
