// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUStencilFaceState = {
	@:optional var compare:GPUCompareFunction;
	@:optional var failOp:GPUStencilOperation;
	@:optional var depthFailOp:GPUStencilOperation;
	@:optional var passOp:GPUStencilOperation;
}
