// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUStorageTextureBindingLayout = {
	@:optional var access:GPUStorageTextureAccess;
	var format:GPUTextureFormat;
	@:optional var viewDimension:GPUTextureViewDimension;
}
