// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUStorageTextureAccess(String) to String {
	var WRITE_ONLY = "write-only";
	var READ_ONLY = "read-only";
	var READ_WRITE = "read-write";
}
