// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUSupportedLimits")
extern class GPUSupportedLimits {
	var maxTextureDimension1D(default, null):Int;
	var maxTextureDimension2D(default, null):Int;
	var maxTextureDimension3D(default, null):Int;
	var maxTextureArrayLayers(default, null):Int;
	var maxBindGroups(default, null):Int;
	var maxBindGroupsPlusVertexBuffers(default, null):Int;
	var maxImmediateSize(default, null):Int;
	var maxBindingsPerBindGroup(default, null):Int;
	var maxDynamicUniformBuffersPerPipelineLayout(default, null):Int;
	var maxDynamicStorageBuffersPerPipelineLayout(default, null):Int;
	var maxSampledTexturesPerShaderStage(default, null):Int;
	var maxSamplersPerShaderStage(default, null):Int;
	var maxStorageBuffersPerShaderStage(default, null):Int;
	var maxStorageBuffersInVertexStage(default, null):Int;
	var maxStorageBuffersInFragmentStage(default, null):Int;
	var maxStorageTexturesPerShaderStage(default, null):Int;
	var maxStorageTexturesInVertexStage(default, null):Int;
	var maxStorageTexturesInFragmentStage(default, null):Int;
	var maxUniformBuffersPerShaderStage(default, null):Int;
	var maxUniformBufferBindingSize(default, null):Float;
	var maxStorageBufferBindingSize(default, null):Float;
	var minUniformBufferOffsetAlignment(default, null):Int;
	var minStorageBufferOffsetAlignment(default, null):Int;
	var maxVertexBuffers(default, null):Int;
	var maxBufferSize(default, null):Float;
	var maxVertexAttributes(default, null):Int;
	var maxVertexBufferArrayStride(default, null):Int;
	var maxInterStageShaderVariables(default, null):Int;
	var maxColorAttachments(default, null):Int;
	var maxColorAttachmentBytesPerSample(default, null):Int;
	var maxComputeWorkgroupStorageSize(default, null):Int;
	var maxComputeInvocationsPerWorkgroup(default, null):Int;
	var maxComputeWorkgroupSizeX(default, null):Int;
	var maxComputeWorkgroupSizeY(default, null):Int;
	var maxComputeWorkgroupSizeZ(default, null):Int;
	var maxComputeWorkgroupsPerDimension(default, null):Int;
}
