// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUSamplerDescriptor = {
	@:optional var label:String;
	@:optional var addressModeU:GPUAddressMode;
	@:optional var addressModeV:GPUAddressMode;
	@:optional var addressModeW:GPUAddressMode;
	@:optional var magFilter:GPUFilterMode;
	@:optional var minFilter:GPUFilterMode;
	@:optional var mipmapFilter:GPUMipmapFilterMode;
	@:optional var lodMinClamp:Float;
	@:optional var lodMaxClamp:Float;
	@:optional var compare:GPUCompareFunction;
	@:optional var maxAnisotropy:Int;
}
