// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUShaderModule")
extern class GPUShaderModule {
	var label:String;
	function getCompilationInfo():js.lib.Promise<GPUCompilationInfo>;
}
