// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUShaderModuleDescriptor = {
	@:optional var label:String;
	var code:String;
	@:optional var compilationHints:Array<GPUShaderModuleCompilationHint>;
}
