// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUTextureAspect(String) to String {
	var ALL = "all";
	var STENCIL_ONLY = "stencil-only";
	var DEPTH_ONLY = "depth-only";
}
