// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUTextureViewDimension(String) to String {
	var V_1D = "1d";
	var V_2D = "2d";
	var V_2D_ARRAY = "2d-array";
	var CUBE = "cube";
	var CUBE_ARRAY = "cube-array";
	var V_3D = "3d";
}
