// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUTexelCopyBufferLayout = {
	@:optional var offset:Float;
	@:optional var bytesPerRow:Int;
	@:optional var rowsPerImage:Int;
}
