// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUTextureSampleType(String) to String {
	var FLOAT = "float";
	var UNFILTERABLE_FLOAT = "unfilterable-float";
	var DEPTH = "depth";
	var SINT = "sint";
	var UINT = "uint";
}
