// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUTextureBindingLayout = {
	@:optional var sampleType:GPUTextureSampleType;
	@:optional var viewDimension:GPUTextureViewDimension;
	@:optional var multisampled:Bool;
}
