// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUTextureDescriptor = {
	@:optional var label:String;
	var size:Dynamic;
	@:optional var mipLevelCount:Int;
	@:optional var sampleCount:Int;
	@:optional var dimension:GPUTextureDimension;
	var format:GPUTextureFormat;
	var usage:Int;
	@:optional var viewFormats:Array<GPUTextureFormat>;
	@:optional var textureBindingViewDimension:GPUTextureViewDimension;
}
