// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUTextureViewDescriptor = {
	@:optional var label:String;
	@:optional var format:GPUTextureFormat;
	@:optional var dimension:GPUTextureViewDimension;
	@:optional var usage:Int;
	@:optional var aspect:GPUTextureAspect;
	@:optional var baseMipLevel:Int;
	@:optional var mipLevelCount:Int;
	@:optional var baseArrayLayer:Int;
	@:optional var arrayLayerCount:Int;
	@:optional var swizzle:String;
}
