// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUTexture")
extern class GPUTexture {
	var width(default, null):Int;
	var height(default, null):Int;
	var depthOrArrayLayers(default, null):Int;
	var mipLevelCount(default, null):Int;
	var sampleCount(default, null):Int;
	var dimension(default, null):GPUTextureDimension;
	var format(default, null):GPUTextureFormat;
	var usage(default, null):Int;
	var textureBindingViewDimension(default, null):Dynamic;
	var label:String;
	function createView(?descriptor:GPUTextureViewDescriptor):GPUTextureView;
	function destroy():Void;
}
