// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUTexelCopyTextureInfo = {
	var texture:GPUTexture;
	@:optional var mipLevel:Int;
	@:optional var origin:Dynamic;
	@:optional var aspect:GPUTextureAspect;
}
