// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("GPUUncapturedErrorEvent")
extern class GPUUncapturedErrorEvent extends js.html.Event {
	var error(default, null):GPUError;
}
