// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

enum abstract GPUVertexFormat(String) to String {
	var UINT8 = "uint8";
	var UINT8X2 = "uint8x2";
	var UINT8X4 = "uint8x4";
	var SINT8 = "sint8";
	var SINT8X2 = "sint8x2";
	var SINT8X4 = "sint8x4";
	var UNORM8 = "unorm8";
	var UNORM8X2 = "unorm8x2";
	var UNORM8X4 = "unorm8x4";
	var SNORM8 = "snorm8";
	var SNORM8X2 = "snorm8x2";
	var SNORM8X4 = "snorm8x4";
	var UINT16 = "uint16";
	var UINT16X2 = "uint16x2";
	var UINT16X4 = "uint16x4";
	var SINT16 = "sint16";
	var SINT16X2 = "sint16x2";
	var SINT16X4 = "sint16x4";
	var UNORM16 = "unorm16";
	var UNORM16X2 = "unorm16x2";
	var UNORM16X4 = "unorm16x4";
	var SNORM16 = "snorm16";
	var SNORM16X2 = "snorm16x2";
	var SNORM16X4 = "snorm16x4";
	var FLOAT16 = "float16";
	var FLOAT16X2 = "float16x2";
	var FLOAT16X4 = "float16x4";
	var FLOAT32 = "float32";
	var FLOAT32X2 = "float32x2";
	var FLOAT32X3 = "float32x3";
	var FLOAT32X4 = "float32x4";
	var UINT32 = "uint32";
	var UINT32X2 = "uint32x2";
	var UINT32X3 = "uint32x3";
	var UINT32X4 = "uint32x4";
	var SINT32 = "sint32";
	var SINT32X2 = "sint32x2";
	var SINT32X3 = "sint32x3";
	var SINT32X4 = "sint32x4";
	var UNORM10_10_10_2 = "unorm10-10-10-2";
	var UNORM8X4_BGRA = "unorm8x4-bgra";
	var SNORM10_10_10_2 = "snorm10-10-10-2";
}
