// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

typedef GPUVertexBufferLayout = {
	var arrayStride:Float;
	@:optional var stepMode:GPUVertexStepMode;
	var attributes:Array<GPUVertexAttribute>;
}
