// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.

package gpu.js;

@:native("WGSLLanguageFeatures")
extern class WGSLLanguageFeatures {
	var size(default, null):Int;
	function has(value:String):Bool;
}
