fn main() {
    let api = xgpu_bindgen::gpu_api();
    let idl = xgpu_bindgen::WEBGPU_IDL;
    let generated =
        xgpu_bindgen::generate_caribou("gpu", &api, idl).expect("valid GPU binding declarations");
    let path = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    std::fs::write(path.join("gpu.rs"), generated).unwrap();
    // The wire to a browser's WebGPU: the plugin's encoder, and the GPU
    // agent's decoder, which a web build carries for the program to ship.
    // The wire also carries the canvas, whose size the agent sets.
    let wire = xgpu_bindgen::wire::wire(&format!("{idl}\n{}", xgpu_bindgen::CANVAS_IDL))
        .expect("the WebGPU IDL generates its wire");
    std::fs::write(path.join("gpu_wire.rs"), wire.rust).unwrap();
    // The agent, and the page's shim that starts it.
    let agent = wire.js + AGENT_START;
    // What a page runs for the plugin, which the program ships beside it.
    let page = path.join("page");
    std::fs::create_dir_all(&page).unwrap();
    std::fs::write(page.join("gpu_agent.mjs"), agent).unwrap();
    std::fs::write(page.join("gpu.mjs"), PAGE_SHIM).unwrap();
    // For a WASI program, the backend the members call: what src/web.rs
    // defines, and a refusal for the rest.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("wasi") {
        let web = include_str!("src/web.rs");
        let backend =
            xgpu_bindgen::web_backend("gpu", &api, idl, web).expect("the web backend generates");
        std::fs::write(path.join("gpu_web_backend.rs"), backend).unwrap();
    }
}

/// The GPU agent's start, after the generated wire: the browser's GPU under
/// handle 1 and, when its starter gives it the page's canvas, the canvas's
/// WebGPU context under handle 2, the program's surface, and the canvas
/// itself under handle 3, whose size is its drawing buffer's. A batch that drew
/// on the canvas counts as run once the frame reached the page, which paces
/// a program that draws to the display.
const AGENT_START: &str = r#"
if (typeof WorkerGlobalScope !== "undefined") {
  start(
    (data) => {
      const roots = new Map([[1, navigator.gpu]]);
      if (data.canvas) {
        roots.set(2, data.canvas.getContext("webgpu"));
        roots.set(3, data.canvas);
      }
      return roots;
    },
    (wire) => {
      const context = wire.objects.get(2);
      if (!context) return;
      let drew = false;
      const current = context.getCurrentTexture.bind(context);
      context.getCurrentTexture = () => {
        drew = true;
        return current();
      };
      wire.after = () => {
        if (!drew) return;
        drew = false;
        return new Promise((resolve) =>
          typeof requestAnimationFrame === "function"
            ? requestAnimationFrame(resolve)
            : setTimeout(resolve, 16),
        );
      };
    },
  );
}
"#;

/// The GPU plugin's shim, which the page imports on its own thread: it
/// starts the agent and gives it the page's canvas, whose drawing buffer
/// the agent then owns.
const PAGE_SHIM: &str = r#"// Generated by the GPU plugin's build: its part of the page.

/// Start the GPU agent for the program at `memory`, whose mailbox is at
/// `address`, drawing on `canvas`.
export function start({ memory, address, canvas }) {
  const agent = new Worker(new URL("./gpu_agent.mjs", import.meta.url), { type: "module" });
  agent.onerror = (e) => console.error(`gpu agent: ${e.message ?? "did not start"}`);
  let surface = null;
  if (canvas) {
    canvas.hidden = false;
    surface = canvas.transferControlToOffscreen();
  }
  agent.postMessage({ memory, address, canvas: surface }, surface ? [surface] : []);
}
"#;
