//! Browser-native Haxe externs generated directly from WebGPU's WebIDL.

use std::collections::{BTreeMap, HashSet};

use x_idl::haxe::File;
use crate::idl::{Int, Ty};

const PACKAGE: &str = "gpu.js";
const HEADER: &str = "// GENERATED by xgpu-bindgen from the vendored WebGPU IDL. DO NOT EDIT.\n\n";

/// Generate Haxe JavaScript extern classes, dictionaries and string enums.
pub fn generate(webidl: &str) -> Result<Vec<File>, String> {
    let model = crate::idl::parse(webidl)?;
    let mut files = Vec::new();

    for (name, values) in &model.enums {
        let variants = values
            .iter()
            .map(|value| format!("\tvar {} = {:?};", constant(value), value))
            .collect::<Vec<_>>()
            .join("\n");
        files.push(source(
            name,
            format!("enum abstract {name}(String) to String {{\n{variants}\n}}\n"),
        ));
    }

    for dictionary in &model.dictionaries {
        let fields = model
            .dictionary_members(&dictionary.name)
            .into_iter()
            .map(|member| {
                let (metadata, name) = member_name(&member.name);
                let optional = if member.required { "" } else { "@:optional " };
                format!(
                    "\t{metadata}{optional}var {name}:{};",
                    haxe_type(&member.ty)
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        files.push(source(
            &dictionary.name,
            format!("typedef {} = {{\n{fields}\n}}\n", dictionary.name),
        ));
    }

    for interface in &model.interfaces {
        let parent = interface
            .inherits
            .as_deref()
            .map(|name| format!(" extends {}", external_type(name)))
            .unwrap_or_default();
        let mut body = Vec::new();
        let mut attributes = HashSet::new();
        for attribute in &interface.attributes {
            if !attributes.insert(attribute.name.clone()) {
                continue;
            }
            let (metadata, name) = member_name(&attribute.name);
            let access = if attribute.readonly {
                "(default, null)"
            } else {
                ""
            };
            body.push(format!(
                "\t{metadata}var {name}{access}:{};",
                haxe_type(&attribute.ty)
            ));
        }

        let mut operations: BTreeMap<&str, Vec<_>> = BTreeMap::new();
        for operation in &interface.operations {
            operations
                .entry(operation.name.as_str())
                .or_default()
                .push(operation);
        }
        for overloads in operations.values() {
            let operation = overloads[overloads.len() - 1];
            let (metadata, name) = member_name(&operation.name);
            for overload in &overloads[..overloads.len() - 1] {
                body.push(format!(
                    "\t@:overload(function({}):{} {{}})",
                    arguments(&overload.args),
                    haxe_type(&overload.ret)
                ));
            }
            body.push(format!(
                "\t{metadata}function {name}({}):{};",
                arguments(&operation.args),
                haxe_type(&operation.ret)
            ));
        }
        if let Some(element) = &interface.setlike {
            let element = haxe_type(element);
            body.push("\tvar size(default, null):Int;".into());
            body.push(format!("\tfunction has(value:{element}):Bool;"));
        }
        files.push(source(
            &interface.name,
            format!(
                "@:native({:?})\nextern class {}{} {{\n{}\n}}\n",
                interface.name,
                interface.name,
                parent,
                body.join("\n")
            ),
        ));
    }

    files.push(source(
        "WebGPU",
        "@:native(\"navigator\")\nextern class WebGPU {\n\tstatic var gpu(default, null):GPU;\n}\n"
            .into(),
    ));
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}

fn source(name: &str, body: String) -> File {
    File {
        path: format!("{}/{name}.hx", PACKAGE.replace('.', "/")),
        source: format!("{HEADER}package {PACKAGE};\n\n{body}"),
    }
}

fn arguments(args: &[crate::idl::Arg]) -> String {
    args.iter()
        .map(|arg| {
            let (metadata, name) = member_name(&arg.name);
            let ty = haxe_type(&arg.ty);
            if arg.variadic {
                format!("{metadata}...{name}:haxe.Rest<{ty}>")
            } else if arg.optional {
                format!("{metadata}?{name}:{ty}")
            } else {
                format!("{metadata}{name}:{ty}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn haxe_type(ty: &Ty) -> String {
    match ty {
        Ty::Undefined => "Void".into(),
        Ty::Boolean => "Bool".into(),
        Ty::Integer(Int::I64 | Int::U64) | Ty::Float(_) => "Float".into(),
        Ty::Integer(_) => "Int".into(),
        Ty::String => "String".into(),
        Ty::Bytes => "js.lib.BufferSource".into(),
        Ty::Enum(name) | Ty::Interface(name) | Ty::Dictionary(name) => name.clone(),
        Ty::Sequence(inner) => format!("Array<{}>", haxe_type(inner)),
        Ty::Record(inner) => format!("haxe.DynamicAccess<{}>", haxe_type(inner)),
        Ty::Nullable(inner) => format!("Null<{}>", haxe_type(inner)),
        Ty::Union(_, _) => "Dynamic".into(),
        Ty::Promise(inner) => format!("js.lib.Promise<{}>", haxe_type(inner)),
        Ty::Opaque(name) => external_type(name),
    }
}

fn external_type(name: &str) -> String {
    match name {
        "EventTarget" => "js.html.EventTarget".into(),
        "Event" => "js.html.Event".into(),
        "Blob" => "js.html.Blob".into(),
        "ImageBitmap" => "js.html.ImageBitmap".into(),
        "HTMLCanvasElement" => "js.html.CanvasElement".into(),
        "HTMLVideoElement" => "js.html.VideoElement".into(),
        "undefined" => "Void".into(),
        _ => "Dynamic".into(),
    }
}

fn member_name(name: &str) -> (String, String) {
    const KEYWORDS: &[&str] = &[
        "break",
        "case",
        "cast",
        "catch",
        "class",
        "continue",
        "default",
        "do",
        "dynamic",
        "else",
        "enum",
        "extends",
        "extern",
        "false",
        "final",
        "for",
        "function",
        "if",
        "implements",
        "import",
        "in",
        "inline",
        "interface",
        "macro",
        "new",
        "null",
        "override",
        "package",
        "private",
        "public",
        "return",
        "static",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typedef",
        "untyped",
        "using",
        "var",
        "while",
    ];
    if KEYWORDS.contains(&name) {
        (format!("@:native({name:?}) "), format!("{name}_"))
    } else {
        (String::new(), name.into())
    }
}

fn constant(value: &str) -> String {
    let mut name = value
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| part.to_ascii_uppercase())
        .collect::<Vec<_>>()
        .join("_");
    if name.is_empty() {
        name.push_str("EMPTY");
    } else if name.starts_with(|c: char| c.is_ascii_digit()) {
        name.insert_str(0, "V_");
    }
    name
}

#[cfg(test)]
mod tests {
    #[test]
    fn complete_webgpu_externs_are_generated() {
        let files = super::generate(crate::WEBGPU_IDL).unwrap();
        let device = files
            .iter()
            .find(|file| file.path == "gpu/js/GPUDevice.hx")
            .unwrap();
        assert!(device.source.starts_with("// GENERATED"));
        assert!(device.source.contains("extern class GPUDevice"));
        assert!(device.source.contains("function createBuffer"));
        assert!(
            files
                .iter()
                .any(|file| file.path == "gpu/js/GPUTextureFormat.hx")
        );
        assert!(files.iter().any(|file| file.path == "gpu/js/WebGPU.hx"));
    }
}
